/*
 * This file is generated by jOOQ.
 */
package com.cl.repository.tables.pojos;


import com.cl.framework.plugin.jooq.generate.VertxPojo;
import com.cl.repository.tables.interfaces.IClCodeConfig;

import java.time.LocalDateTime;


import static com.cl.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 代码配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClCodeConfig implements VertxPojo, IClCodeConfig {

    private static final long serialVersionUID = 1L;

    private Long          id;
    private LocalDateTime gmtCreate;
    private LocalDateTime gmtModified;
    private String        creator;
    private String        editor;
    private String        dsl;
    private String        content;
    private String        status;
    private Short         isDelete;
    private Long          tenantId;
    private String        codeName;
    private String        desc;
    private String        serverAddress;
    private String        methodName;

    public ClCodeConfig() {}

    public ClCodeConfig(IClCodeConfig value) {
        this.id = value.getId();
        this.gmtCreate = value.getGmtCreate();
        this.gmtModified = value.getGmtModified();
        this.creator = value.getCreator();
        this.editor = value.getEditor();
        this.dsl = value.getDsl();
        this.content = value.getContent();
        this.status = value.getStatus();
        this.isDelete = value.getIsDelete();
        this.tenantId = value.getTenantId();
        this.codeName = value.getCodeName();
        this.desc = value.getDesc();
        this.serverAddress = value.getServerAddress();
        this.methodName = value.getMethodName();
    }

    public ClCodeConfig(
        Long          id,
        LocalDateTime gmtCreate,
        LocalDateTime gmtModified,
        String        creator,
        String        editor,
        String        dsl,
        String        content,
        String        status,
        Short         isDelete,
        Long          tenantId,
        String        codeName,
        String        desc,
        String        serverAddress,
        String        methodName
    ) {
        this.id = id;
        this.gmtCreate = gmtCreate;
        this.gmtModified = gmtModified;
        this.creator = creator;
        this.editor = editor;
        this.dsl = dsl;
        this.content = content;
        this.status = status;
        this.isDelete = isDelete;
        this.tenantId = tenantId;
        this.codeName = codeName;
        this.desc = desc;
        this.serverAddress = serverAddress;
        this.methodName = methodName;
    }

        public ClCodeConfig(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }

    /**
     * Getter for <code>public.cl_code_config.id</code>.
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.cl_code_config.id</code>.
     */
    @Override
    public ClCodeConfig setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.gmt_create</code>. 创建时间
     */
    @Override
    public LocalDateTime getGmtCreate() {
        return this.gmtCreate;
    }

    /**
     * Setter for <code>public.cl_code_config.gmt_create</code>. 创建时间
     */
    @Override
    public ClCodeConfig setGmtCreate(LocalDateTime gmtCreate) {
        this.gmtCreate = gmtCreate;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.gmt_modified</code>. 修改时间
     */
    @Override
    public LocalDateTime getGmtModified() {
        return this.gmtModified;
    }

    /**
     * Setter for <code>public.cl_code_config.gmt_modified</code>. 修改时间
     */
    @Override
    public ClCodeConfig setGmtModified(LocalDateTime gmtModified) {
        this.gmtModified = gmtModified;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.creator</code>. 创建人
     */
    @Override
    public String getCreator() {
        return this.creator;
    }

    /**
     * Setter for <code>public.cl_code_config.creator</code>. 创建人
     */
    @Override
    public ClCodeConfig setCreator(String creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.editor</code>. 创建人
     */
    @Override
    public String getEditor() {
        return this.editor;
    }

    /**
     * Setter for <code>public.cl_code_config.editor</code>. 创建人
     */
    @Override
    public ClCodeConfig setEditor(String editor) {
        this.editor = editor;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.dsl</code>. 语言类型
     */
    @Override
    public String getDsl() {
        return this.dsl;
    }

    /**
     * Setter for <code>public.cl_code_config.dsl</code>. 语言类型
     */
    @Override
    public ClCodeConfig setDsl(String dsl) {
        this.dsl = dsl;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.content</code>. 代码内容
     */
    @Override
    public String getContent() {
        return this.content;
    }

    /**
     * Setter for <code>public.cl_code_config.content</code>. 代码内容
     */
    @Override
    public ClCodeConfig setContent(String content) {
        this.content = content;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.status</code>. publish ,
     * normal，disable
     */
    @Override
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.cl_code_config.status</code>. publish ,
     * normal，disable
     */
    @Override
    public ClCodeConfig setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return this.isDelete;
    }

    /**
     * Setter for <code>public.cl_code_config.is_delete</code>. 0 否 1 是
     */
    @Override
    public ClCodeConfig setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return this.tenantId;
    }

    /**
     * Setter for <code>public.cl_code_config.tenant_id</code>. 租户id
     */
    @Override
    public ClCodeConfig setTenantId(Long tenantId) {
        this.tenantId = tenantId;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.code_name</code>.
     */
    @Override
    public String getCodeName() {
        return this.codeName;
    }

    /**
     * Setter for <code>public.cl_code_config.code_name</code>.
     */
    @Override
    public ClCodeConfig setCodeName(String codeName) {
        this.codeName = codeName;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.desc</code>.
     */
    @Override
    public String getDesc() {
        return this.desc;
    }

    /**
     * Setter for <code>public.cl_code_config.desc</code>.
     */
    @Override
    public ClCodeConfig setDesc(String desc) {
        this.desc = desc;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.server_address</code>. 服务地址 唯一
     */
    @Override
    public String getServerAddress() {
        return this.serverAddress;
    }

    /**
     * Setter for <code>public.cl_code_config.server_address</code>. 服务地址 唯一
     */
    @Override
    public ClCodeConfig setServerAddress(String serverAddress) {
        this.serverAddress = serverAddress;
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.method_name</code>. 方法名
     */
    @Override
    public String getMethodName() {
        return this.methodName;
    }

    /**
     * Setter for <code>public.cl_code_config.method_name</code>. 方法名
     */
    @Override
    public ClCodeConfig setMethodName(String methodName) {
        this.methodName = methodName;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ClCodeConfig other = (ClCodeConfig) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.gmtCreate == null) {
            if (other.gmtCreate != null)
                return false;
        }
        else if (!this.gmtCreate.equals(other.gmtCreate))
            return false;
        if (this.gmtModified == null) {
            if (other.gmtModified != null)
                return false;
        }
        else if (!this.gmtModified.equals(other.gmtModified))
            return false;
        if (this.creator == null) {
            if (other.creator != null)
                return false;
        }
        else if (!this.creator.equals(other.creator))
            return false;
        if (this.editor == null) {
            if (other.editor != null)
                return false;
        }
        else if (!this.editor.equals(other.editor))
            return false;
        if (this.dsl == null) {
            if (other.dsl != null)
                return false;
        }
        else if (!this.dsl.equals(other.dsl))
            return false;
        if (this.content == null) {
            if (other.content != null)
                return false;
        }
        else if (!this.content.equals(other.content))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.isDelete == null) {
            if (other.isDelete != null)
                return false;
        }
        else if (!this.isDelete.equals(other.isDelete))
            return false;
        if (this.tenantId == null) {
            if (other.tenantId != null)
                return false;
        }
        else if (!this.tenantId.equals(other.tenantId))
            return false;
        if (this.codeName == null) {
            if (other.codeName != null)
                return false;
        }
        else if (!this.codeName.equals(other.codeName))
            return false;
        if (this.desc == null) {
            if (other.desc != null)
                return false;
        }
        else if (!this.desc.equals(other.desc))
            return false;
        if (this.serverAddress == null) {
            if (other.serverAddress != null)
                return false;
        }
        else if (!this.serverAddress.equals(other.serverAddress))
            return false;
        if (this.methodName == null) {
            if (other.methodName != null)
                return false;
        }
        else if (!this.methodName.equals(other.methodName))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.gmtCreate == null) ? 0 : this.gmtCreate.hashCode());
        result = prime * result + ((this.gmtModified == null) ? 0 : this.gmtModified.hashCode());
        result = prime * result + ((this.creator == null) ? 0 : this.creator.hashCode());
        result = prime * result + ((this.editor == null) ? 0 : this.editor.hashCode());
        result = prime * result + ((this.dsl == null) ? 0 : this.dsl.hashCode());
        result = prime * result + ((this.content == null) ? 0 : this.content.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.isDelete == null) ? 0 : this.isDelete.hashCode());
        result = prime * result + ((this.tenantId == null) ? 0 : this.tenantId.hashCode());
        result = prime * result + ((this.codeName == null) ? 0 : this.codeName.hashCode());
        result = prime * result + ((this.desc == null) ? 0 : this.desc.hashCode());
        result = prime * result + ((this.serverAddress == null) ? 0 : this.serverAddress.hashCode());
        result = prime * result + ((this.methodName == null) ? 0 : this.methodName.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ClCodeConfig (");

        sb.append(id);
        sb.append(", ").append(gmtCreate);
        sb.append(", ").append(gmtModified);
        sb.append(", ").append(creator);
        sb.append(", ").append(editor);
        sb.append(", ").append(dsl);
        sb.append(", ").append(content);
        sb.append(", ").append(status);
        sb.append(", ").append(isDelete);
        sb.append(", ").append(tenantId);
        sb.append(", ").append(codeName);
        sb.append(", ").append(desc);
        sb.append(", ").append(serverAddress);
        sb.append(", ").append(methodName);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClCodeConfig from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setCreator(from.getCreator());
        setEditor(from.getEditor());
        setDsl(from.getDsl());
        setContent(from.getContent());
        setStatus(from.getStatus());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
        setCodeName(from.getCodeName());
        setDesc(from.getDesc());
        setServerAddress(from.getServerAddress());
        setMethodName(from.getMethodName());
    }

    @Override
    public <E extends IClCodeConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
