/*
 * This file is generated by jOOQ.
 */
package com.cl.repository.tables.records;


import com.cl.framework.plugin.jooq.generate.VertxPojo;
import com.cl.repository.tables.ClCodeConfig;
import com.cl.repository.tables.interfaces.IClCodeConfig;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


import static com.cl.framework.plugin.jooq.generate.VertxPojo.*;
/**
 * 代码配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClCodeConfigRecord extends UpdatableRecordImpl<ClCodeConfigRecord> implements VertxPojo, Record14<Long, LocalDateTime, LocalDateTime, String, String, String, String, String, Short, Long, String, String, String, String>, IClCodeConfig {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cl_code_config.id</code>.
     */
    @Override
    public ClCodeConfigRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.id</code>.
     */
    @Override
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cl_code_config.gmt_create</code>. 创建时间
     */
    @Override
    public ClCodeConfigRecord setGmtCreate(LocalDateTime value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.gmt_create</code>. 创建时间
     */
    @Override
    public LocalDateTime getGmtCreate() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>public.cl_code_config.gmt_modified</code>. 修改时间
     */
    @Override
    public ClCodeConfigRecord setGmtModified(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.gmt_modified</code>. 修改时间
     */
    @Override
    public LocalDateTime getGmtModified() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.cl_code_config.creator</code>. 创建人
     */
    @Override
    public ClCodeConfigRecord setCreator(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.creator</code>. 创建人
     */
    @Override
    public String getCreator() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.cl_code_config.editor</code>. 创建人
     */
    @Override
    public ClCodeConfigRecord setEditor(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.editor</code>. 创建人
     */
    @Override
    public String getEditor() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.cl_code_config.dsl</code>. 语言类型
     */
    @Override
    public ClCodeConfigRecord setDsl(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.dsl</code>. 语言类型
     */
    @Override
    public String getDsl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.cl_code_config.content</code>. 代码内容
     */
    @Override
    public ClCodeConfigRecord setContent(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.content</code>. 代码内容
     */
    @Override
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.cl_code_config.status</code>. publish ,
     * normal，disable
     */
    @Override
    public ClCodeConfigRecord setStatus(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.status</code>. publish ,
     * normal，disable
     */
    @Override
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.cl_code_config.is_delete</code>. 0 否 1 是
     */
    @Override
    public ClCodeConfigRecord setIsDelete(Short value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.is_delete</code>. 0 否 1 是
     */
    @Override
    public Short getIsDelete() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.cl_code_config.tenant_id</code>. 租户id
     */
    @Override
    public ClCodeConfigRecord setTenantId(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.tenant_id</code>. 租户id
     */
    @Override
    public Long getTenantId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.cl_code_config.code_name</code>.
     */
    @Override
    public ClCodeConfigRecord setCodeName(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.code_name</code>.
     */
    @Override
    public String getCodeName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.cl_code_config.desc</code>.
     */
    @Override
    public ClCodeConfigRecord setDesc(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.desc</code>.
     */
    @Override
    public String getDesc() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.cl_code_config.server_address</code>. 服务地址 唯一
     */
    @Override
    public ClCodeConfigRecord setServerAddress(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.server_address</code>. 服务地址 唯一
     */
    @Override
    public String getServerAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.cl_code_config.method_name</code>. 方法名
     */
    @Override
    public ClCodeConfigRecord setMethodName(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.cl_code_config.method_name</code>. 方法名
     */
    @Override
    public String getMethodName() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Long, LocalDateTime, LocalDateTime, String, String, String, String, String, Short, Long, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Long, LocalDateTime, LocalDateTime, String, String, String, String, String, Short, Long, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ClCodeConfig.CL_CODE_CONFIG.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return ClCodeConfig.CL_CODE_CONFIG.GMT_CREATE;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ClCodeConfig.CL_CODE_CONFIG.GMT_MODIFIED;
    }

    @Override
    public Field<String> field4() {
        return ClCodeConfig.CL_CODE_CONFIG.CREATOR;
    }

    @Override
    public Field<String> field5() {
        return ClCodeConfig.CL_CODE_CONFIG.EDITOR;
    }

    @Override
    public Field<String> field6() {
        return ClCodeConfig.CL_CODE_CONFIG.DSL;
    }

    @Override
    public Field<String> field7() {
        return ClCodeConfig.CL_CODE_CONFIG.CONTENT;
    }

    @Override
    public Field<String> field8() {
        return ClCodeConfig.CL_CODE_CONFIG.STATUS;
    }

    @Override
    public Field<Short> field9() {
        return ClCodeConfig.CL_CODE_CONFIG.IS_DELETE;
    }

    @Override
    public Field<Long> field10() {
        return ClCodeConfig.CL_CODE_CONFIG.TENANT_ID;
    }

    @Override
    public Field<String> field11() {
        return ClCodeConfig.CL_CODE_CONFIG.CODE_NAME;
    }

    @Override
    public Field<String> field12() {
        return ClCodeConfig.CL_CODE_CONFIG.DESC;
    }

    @Override
    public Field<String> field13() {
        return ClCodeConfig.CL_CODE_CONFIG.SERVER_ADDRESS;
    }

    @Override
    public Field<String> field14() {
        return ClCodeConfig.CL_CODE_CONFIG.METHOD_NAME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime component3() {
        return getGmtModified();
    }

    @Override
    public String component4() {
        return getCreator();
    }

    @Override
    public String component5() {
        return getEditor();
    }

    @Override
    public String component6() {
        return getDsl();
    }

    @Override
    public String component7() {
        return getContent();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public Short component9() {
        return getIsDelete();
    }

    @Override
    public Long component10() {
        return getTenantId();
    }

    @Override
    public String component11() {
        return getCodeName();
    }

    @Override
    public String component12() {
        return getDesc();
    }

    @Override
    public String component13() {
        return getServerAddress();
    }

    @Override
    public String component14() {
        return getMethodName();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getGmtCreate();
    }

    @Override
    public LocalDateTime value3() {
        return getGmtModified();
    }

    @Override
    public String value4() {
        return getCreator();
    }

    @Override
    public String value5() {
        return getEditor();
    }

    @Override
    public String value6() {
        return getDsl();
    }

    @Override
    public String value7() {
        return getContent();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public Short value9() {
        return getIsDelete();
    }

    @Override
    public Long value10() {
        return getTenantId();
    }

    @Override
    public String value11() {
        return getCodeName();
    }

    @Override
    public String value12() {
        return getDesc();
    }

    @Override
    public String value13() {
        return getServerAddress();
    }

    @Override
    public String value14() {
        return getMethodName();
    }

    @Override
    public ClCodeConfigRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value2(LocalDateTime value) {
        setGmtCreate(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value3(LocalDateTime value) {
        setGmtModified(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value4(String value) {
        setCreator(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value5(String value) {
        setEditor(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value6(String value) {
        setDsl(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value7(String value) {
        setContent(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value9(Short value) {
        setIsDelete(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value10(Long value) {
        setTenantId(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value11(String value) {
        setCodeName(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value12(String value) {
        setDesc(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value13(String value) {
        setServerAddress(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord value14(String value) {
        setMethodName(value);
        return this;
    }

    @Override
    public ClCodeConfigRecord values(Long value1, LocalDateTime value2, LocalDateTime value3, String value4, String value5, String value6, String value7, String value8, Short value9, Long value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IClCodeConfig from) {
        setId(from.getId());
        setGmtCreate(from.getGmtCreate());
        setGmtModified(from.getGmtModified());
        setCreator(from.getCreator());
        setEditor(from.getEditor());
        setDsl(from.getDsl());
        setContent(from.getContent());
        setStatus(from.getStatus());
        setIsDelete(from.getIsDelete());
        setTenantId(from.getTenantId());
        setCodeName(from.getCodeName());
        setDesc(from.getDesc());
        setServerAddress(from.getServerAddress());
        setMethodName(from.getMethodName());
    }

    @Override
    public <E extends IClCodeConfig> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClCodeConfigRecord
     */
    public ClCodeConfigRecord() {
        super(ClCodeConfig.CL_CODE_CONFIG);
    }

    /**
     * Create a detached, initialised ClCodeConfigRecord
     */
    public ClCodeConfigRecord(Long id, LocalDateTime gmtCreate, LocalDateTime gmtModified, String creator, String editor, String dsl, String content, String status, Short isDelete, Long tenantId, String codeName, String desc, String serverAddress, String methodName) {
        super(ClCodeConfig.CL_CODE_CONFIG);

        setId(id);
        setGmtCreate(gmtCreate);
        setGmtModified(gmtModified);
        setCreator(creator);
        setEditor(editor);
        setDsl(dsl);
        setContent(content);
        setStatus(status);
        setIsDelete(isDelete);
        setTenantId(tenantId);
        setCodeName(codeName);
        setDesc(desc);
        setServerAddress(serverAddress);
        setMethodName(methodName);
    }

    /**
     * Create a detached, initialised ClCodeConfigRecord
     */
    public ClCodeConfigRecord(com.cl.repository.tables.pojos.ClCodeConfig value) {
        super(ClCodeConfig.CL_CODE_CONFIG);

        if (value != null) {
            setId(value.getId());
            setGmtCreate(value.getGmtCreate());
            setGmtModified(value.getGmtModified());
            setCreator(value.getCreator());
            setEditor(value.getEditor());
            setDsl(value.getDsl());
            setContent(value.getContent());
            setStatus(value.getStatus());
            setIsDelete(value.getIsDelete());
            setTenantId(value.getTenantId());
            setCodeName(value.getCodeName());
            setDesc(value.getDesc());
            setServerAddress(value.getServerAddress());
            setMethodName(value.getMethodName());
        }
    }

        public ClCodeConfigRecord(io.vertx.core.json.JsonObject json) {
                this();
                fromJson(json);
        }
}
