/*
 * This file is generated by jOOQ.
 */
package com.cl.repository;


import com.cl.repository.tables.ClCodeConfig;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CL_CODE_CONFIG_DSL_INDEX = Internal.createIndex(DSL.name("cl_code_config_dsl_index"), ClCodeConfig.CL_CODE_CONFIG, new OrderField[] { ClCodeConfig.CL_CODE_CONFIG.DSL }, false);
    public static final Index CL_CODE_CONFIG_STATUS_INDEX = Internal.createIndex(DSL.name("cl_code_config_status_index"), ClCodeConfig.CL_CODE_CONFIG, new OrderField[] { ClCodeConfig.CL_CODE_CONFIG.STATUS }, false);
}
