/*
 * This file is generated by jOOQ.
 */
package com.cl.repository;


import com.cl.repository.tables.ClCodeConfig;
import com.cl.repository.tables.records.ClCodeConfigRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClCodeConfigRecord> CL_CODE_CONFIG_PK = Internal.createUniqueKey(ClCodeConfig.CL_CODE_CONFIG, DSL.name("cl_code_config_pk"), new TableField[] { ClCodeConfig.CL_CODE_CONFIG.ID }, true);
}
