/*
 * This file is generated by jOOQ.
 */
package com.cl.repository;


import com.cl.repository.tables.ClCodeConfig;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 代码配置
     */
    public static final ClCodeConfig CL_CODE_CONFIG = ClCodeConfig.CL_CODE_CONFIG;
}
